version: "3.9"

services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0      
        networks:
            - elastic
        ports:
            - "9200:9200"    
        environment:
            - discovery.type=single-node
            - ELASTIC_PASSWORD=password
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:8.6.0
        networks:
            - elastic
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch 
        

networks:
    elastic:

